#!/usr/bin/expect

spawn ./start.sh
set timeout 90

expect {
    "Done" {
        puts "Server loaded"
        send "patpat info\n"
        expect {
            "[PatPat] Platform: " {
                exit 0
            }
            timeout
            eof {
                puts "ERROR: server is not launched"
                exit 1
            }
        }
    }
    timeout
    eof {
      puts "ERROR: server is not launched"
        exit 1
    }
}
