name: PatPatPluginFolia
version: ${version}
autors: [
  nikita51bot and ExpertX_DA
]
main: net.lopymine.patpat.plugin.PatPatPlugin
api-version: '1.16'
folia-supported: True
commands:
  patpat:
    description: "Command to configure and control the PatPat Plugin"
    usage: "/patpat (info | list | ratelimit | reload)"
