name: PatPatPlugin
version: '1.0.0'
main: net.lopymine.patpat.plugin.PatPatPlugin
api-version: '1.16'
commands:
  patpat:
    description: "Command to configure and control the PatPat Plugin"
    usage: "/patpat"
