plugins {
	id 'java'
}

description = 'PatPat Plugin API'

group = "net.lopymine.patpat.plugin.api"
version = "1.0.0"

base {
	archivesName = "patpat-plugin-api"
}

java {
	withSourcesJar()
	withJavadocJar()
}

configurations {
	lombokClasspath {
		canBeResolved = true
		extendsFrom(configurations.compileOnly)
	}
}

tasks.register('delombokSources', JavaExec) {
	mainClass.set('lombok.launch.Main')
	args('delombok', 'src/main/java', '-d', 'build/delombok')
	classpath = configurations.lombokClasspath
}

tasks.named('sourcesJar') {
	duplicatesStrategy = DuplicatesStrategy.INCLUDE
	dependsOn('delombokSources')
	from('build/delombok')
}

tasks.named('javadoc', Javadoc) {
	dependsOn('delombokSources')
	source = fileTree('build/delombok')
	classpath = sourceSets.main.compileClasspath
}