plugins {
	id 'java'
}

description = 'PatPat Plugin API'

group = "net.lopymine.patpat.plugin.api"
version = "1.0.0"

base {
	archivesName = "patpat-plugin-api"
}

java {
	withSourcesJar()
	withJavadocJar()
}

tasks.withType(Javadoc).configureEach {
	options.docTitle = "PatPat Plugin API "+version
	options.windowTitle = options.docTitle

	//options.addBooleanOption('Xdoclint:none', true)
}