difficulty=peaceful
enable-rcon=true
generate-structures=false
rcon.password=dockerserver
view-distance=6
spawn-animals=false
spawn-monsters=false
spawn-npcs=false
online-mode=false
allow-nether=false
level-type=minecraft\:flat
server-ip=127.0.0.1